name: Test a branch on canary
on:
  workflow_dispatch:
    inputs:
      COMMIT_SHA:
        description: 'Commit SHA to be tested'
        required: true

env:
  COMMIT_SHA: ${{ github.event.inputs.COMMIT_SHA }}
defaults:
  run:
    shell: pwsh

jobs:
  update_tag:
    name: Update the rc tag to ${{ github.event.inputs.COMMIT_SHA }} commit
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: step-security/harden-runner@34cbc43f0b10c9dda284e663cf43c2ebaf83e956 # v1
      with:
        allowed-endpoints: 
          api.github.com:443
          github.com:443

    - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2
    - name: Update the rc tag
      uses: step-security/publish-action@b438f840875fdcb7d1de4fc3d1d30e86cf6acb5d
      with:
        rc-sha: ${{ env.COMMIT_SHA }}
        rc: true

    - name: Canary test
      uses: docker://ghcr.io/step-security/integration-test/int:latest
      env:
        PAT: ${{ secrets.PAT }}
        canary: true
